#sudo apt update  
#ayuda a resolver el dependency hell porque 
#actualiza la información de los repositorios. De esta forma, el sistema conoce qué versiones de paquetes y dependencias 
#están disponibles, evitando errores causados por información desactualizada al instalar software. 
sudo apt update  
#sudo apt upgrade 
#ayuda a resolver el dependency hell porque actualiza los paquetes instalados a versiones más recientes 
#y compatibles. Esto reduce los conflictos entre dependencias y corrige problemas ocasionados por versiones antiguas de bibliotecas o programas.
sudo apt upgrade